Parabot/Parabot

src/main/java/org/parabot/core/ui/BotUI.java
src/main/java/org/parabot/core/ui/ReflectUI.java
src/main/java/org/parabot/core/ui/ServerSelector.java

This searches for the VALUE that the field currently has.
Doesn't work with PKHonor for some reason.

[FEATURE] Added search function to Reflection Explorer

---

pom.xml
src/test/java/org/parabot/MacAddressUnitTest.java

[TASK] Added unit test for mac address

---

src/main/java/org/parabot/environment/api/utils/Version.java

[BUGFIX] Solved issue with versions with RC

---

.travis.yml

[FEATURE] Added JDK8 as build check to Travis

---

pom.xml
src/main/java/org/parabot/Landing.java
src/main/java/org/parabot/core/Context.java

[FEATURE] Added translations for Context

---

pom.xml

Related to issue #47 and issue #48

[FEATURE] Implemented new internal API

---

src/main/java/org/parabot/Landing.java
src/main/java/org/parabot/core/Configuration.java
src/main/java/org/parabot/core/Core.java

[BUGFIX] Solved issue downloading incorrect latest version

---

pom.xml
src/main/java/org/parabot/Landing.java
src/main/java/org/parabot/core/Configuration.java
src/main/java/org/parabot/core/parsers/randoms/PublicRandoms.java
src/main/java/org/parabot/environment/servers/executers/PublicServerExecuter.java

[FEATURE] Added nightly support for randoms

---

src/main/java/org/parabot/core/Core.java

This line would throw ClassCastException when starting the client.

[BUGFIX] Would throw ClassCastException

---

pom.xml

[TASK] Updated to latest version, ready for V2.6.1

---

.travis.yml
src/main/java/org/parabot/core/Context.java
src/main/java/org/parabot/core/ui/BotUI.java
src/main/java/org/parabot/core/ui/RandomUI.java
src/main/java/org/parabot/environment/randoms/Random.java
src/main/java/org/parabot/environment/randoms/RandomHandler.java
src/main/java/org/parabot/environment/randoms/RandomType.java
src/main/java/org/parabot/environment/scripts/Script.java
src/main/java/org/parabot/environment/scripts/randoms/Random.java
src/main/java/org/parabot/environment/scripts/randoms/RandomHandler.java
src/main/java/org/parabot/environment/servers/executers/ServerExecuter.java

[FEATURE] Added random types

---

pom.xml

[TASK] Version Bump

---

src/main/java/org/parabot/core/asm/RedirectClassAdapter.java
src/main/java/org/parabot/core/asm/redirect/ClassLoaderRedirect.java

Until further investigation
Related to issue #155

[BUGFIX] Temp removal of ClassLoaderRedirect

---

.travis.yml
README.md
pom.xml

[TASK] Incremented version to 2.6.3

---

src/main/java/org/parabot/core/asm/redirect/RuntimeRedirect.java

For `exec(Ljava/lang/Runtime;[Ljava/lang/String;)Ljava/lang/Process;`
Solving issue #161

[BUGFIX] Added redirect for issue #161

---

.travis.yml
pom.xml
src/main/java/org/parabot/environment/randoms/RandomHandler.java

[BUGFIX] Added try catch and logger message for failed randoms

---

src/main/java/org/parabot/core/Core.java

[BUGFIX] Remade validateCache

---

src/main/java/org/parabot/core/asm/redirect/ProcessBuilderRedirect.java

[FEATURE] Added redirectErrorStream

---

src/main/java/org/parabot/environment/Environment.java

Allowing to load libraries into the environment, seperated from loading the entire environment
Various areas of the codebase have been worked on by different people in recent years, so if you are unfamiliar with the general area you're working in, please feel free to chat with people who have experience in …

[TASK] Separated library loading

---

pom.xml
src/main/java/org/parabot/core/lib/jpushbullet/JPushBullet.java

[FEATURE] Push Bullet Notifications

---

src/main/java/org/parabot/core/Context.java
src/main/java/org/parabot/core/ui/BotUI.java
src/main/java/org/parabot/environment/servers/executers/ServerExecuter.java

[BUGFIX] Keep Tools menu

---

src/main/java/org/parabot/core/asm/redirect/SystemRedirect.java

[BUGFIX] Replaced the output to verbose only

---

.travis.yml
pom.xml
src/main/java/org/parabot/core/asm/redirect/SystemRedirect.java
src/main/java/org/parabot/core/ui/Logger.java

[BUGFIX] Logger#addMessage

---

src/main/java/org/parabot/Landing.java
src/main/java/org/parabot/core/Core.java
src/main/java/org/parabot/core/arguments/LandingArgument.java
src/main/java/org/parabot/core/arguments/landing/Auth.java
src/main/java/org/parabot/core/arguments/landing/ClearCache.java
src/main/java/org/parabot/core/arguments/landing/CreateDirs.java
src/main/java/org/parabot/core/arguments/landing/Dump.java
src/main/java/org/parabot/core/arguments/landing/Local.java
src/main/java/org/parabot/core/arguments/landing/Mac.java
src/main/java/org/parabot/core/arguments/landing/NoSec.java
src/main/java/org/parabot/core/arguments/landing/NoValidation.java
src/main/java/org/parabot/core/arguments/landing/Proxy.java
src/main/java/org/parabot/core/arguments/landing/ScriptsBin.java
src/main/java/org/parabot/core/arguments/landing/Server.java
src/main/java/org/parabot/core/arguments/landing/ServersBin.java
src/main/java/org/parabot/core/arguments/landing/Verbose.java
src/main/java/org/parabot/core/arguments/landing/WithLocal.java

[FEATURE] Added the remaining arguments

---

src/main/java/org/parabot/core/asm/redirect/ClassRedirect.java

[BUGFIX] Added desiredAssertionStatus

---

src/main/java/org/parabot/core/asm/redirect/ThreadRedirect.java

Thread.setUncaughtExceptionHandler
Your pull request will be tested via Travis CI to …

[BUGFIX] Solves NoSuchMethodError for Thread

---

src/main/java/org/parabot/core/ui/BotUI.java

[BUGFIX] Removed JFrame from screenshot

---

src/main/java/org/parabot/Landing.java
src/main/java/org/parabot/core/Core.java
src/main/java/org/parabot/core/ui/utils/UILog.java

Related to issue #195
Your pull request will be tested via Travis CI to automatically …

[FEATURE] Alert of new version

---

.travis.yml
pom.xml

[RELEASE] Release of V2.6.6

---

src/main/java/org/parabot/core/reflect/RefClass.java

RefClass#getMethod didn't work with parameters

[BUGFIX] A bug where reflection method lookup did not work

---

.travis.yml
src/main/java/org/parabot/core/asm/redirect/ThreadRedirect.java
src/main/java/org/parabot/core/asm/redirect/ToolkitRedirect.java

[BUGFIX] Solving currentThread null return

---

.travis.yml

[BUGFIX] Set deployment requirement to openjdk7

---

.travis.yml
README.md
pom.xml
src/main/java/org/parabot/core/ui/BotUI.java

[BUGFIX] Fixed height on screenshots

---

src/main/java/org/parabot/environment/scripts/Script.java

Allows users to add randoms though scripts.
Your pull request will be tested via Travis …

[FEATURE] Added Randoms to Script

---

.travis.yml
src/main/java/org/parabot/environment/api/utils/Timer.java

[Feature] Added days into Timer

---

src/main/java/org/parabot/core/asm/RedirectClassAdapter.java

Add getter

---

src/main/java/org/parabot/Landing.java
src/main/java/org/parabot/core/Core.java

Docs for -debug

---

src/main/java/org/parabot/environment/api/utils/Time.java

Added conditional sleep with minimum timeout

---

src/main/java/org/parabot/core/asm/redirect/ClassRedirect.java

Added getResource() to catch error and fixed inverted statement

Fix for issue #288

---

src/main/java/org/parabot/core/Configuration.java
src/main/java/org/parabot/core/ui/utils/UILog.java
src/main/java/org/parabot/environment/servers/ServerProvider.java

Feature requested by @PBLord 
-Added new alert that allows custom button text
-Redirect user to forums when clicking on report button

Add hook report button

---

pom.xml
src/main/java/org/parabot/core/ui/BotUI.java
src/main/java/org/parabot/core/ui/components/notifications/NotificationUI.java
src/main/java/org/parabot/environment/Environment.java
src/main/resources/storage/ui/notifications.fxml

Depends on [Internal-API#45](https://github.com/Parabot/Internal-API/pull/45)

Replace JavaFX-Application based UIs with FX-embedded-in-swing

---

src/main/java/org/parabot/core/asm/redirect/RuntimeRedirect.java
src/main/java/org/parabot/core/parsers/hooks/HookParser.java
src/main/java/org/parabot/core/parsers/hooks/JSONHookParser.java
src/main/java/org/parabot/core/parsers/hooks/XMLHookParser.java

Allows you to get the parsed interfaces and get classes based on names.

[FEATURE] Added InterfaceMap getter

---

.travis.yml
README.md
pom.xml

Prepares the client for release v2.8
Related to #294

[RELEASE] Prepared for release of v2.8

---

src/main/java/org/parabot/core/asm/redirect/ClassRedirect.java

The code tells more than this description...

[BUGFIX] Set to correct check

---

src/main/java/org/parabot/Landing.java
src/main/java/org/parabot/core/network/proxy/ProxySocket.java

This way you know when you made a typo or when you've given an incorrect/unknown argument

[TASK] Added System.err output if an unknown argument is given

---

src/main/java/org/parabot/core/asm/hooks/HookFile.java
src/main/java/org/parabot/core/forum/AccountManager.java
src/main/java/org/parabot/core/parsers/hooks/HookParser.java
src/main/java/org/parabot/core/parsers/hooks/XMLHookParser.java

Added option to authenticate the user with their API key

[FEATURE] Added hooks authentication

---

.travis.yml
README.md
pom.xml

[TASK] Updated to V2.8.1

---

src/main/java/org/parabot/core/Configuration.java
src/main/java/org/parabot/core/parsers/scripts/ScriptParser.java
src/main/java/org/parabot/core/ui/ScriptSelector.java

- Formatted code
- Added link to BDN scripts page in script selector

 [TASK] Added link to Scripts page

---

src/main/java/org/parabot/core/ui/ScriptSelector.java

Fixed issue when selecting a script in debug mode

[BUGFIX] Fixed null pointer on debug

---

src/main/java/org/parabot/core/asm/redirect/SystemRedirect.java

Returns the entire classpath, except for the Parabot paths

[FEATURE] Added valid class path
